name=FlowSensorLib
version=1.0.2
author=Tunasha,Babatunde Adg
maintainer=Babatunde Adegoke <tunashapcb@gmail.com>
sentence=Reads the amount of liquid that flows through a flow sensor.
paragraph=This library provides non-blocking class that counts pulses from a hall-effect flow sensor, converts them to flow rate (L/min) and accumulated volume (L). Works with any pulse-output flow meter.
category=Sensors
url=https://github.com/Tunasha/FlowSensorLib
architectures=*
includes=FlowSensorLib.h
